blank_issues_enabled: false
contact_links:
    - name: Feature Request
      url: https://github.com/Sellitus/Mage-Code/discussions/categories/feature-requests
      about: Share and vote on feature requests for Mage Code
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=RooVeterinaryInc.mage-code&ssr=false#review-details
      about: Enjoying Mage Code? Leave a review here!
